#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.0 on Sun Mar  9 13:28:25 2025
#

# This is an automatically generated file.
# Manual changes will be overwritten without warning!

import wx
from MainFrame import MainFrame


class GCodeToRapidApp(wx.App):
    def OnInit(self):
        self.frame = MainFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class GCodeToRapidApp

if __name__ == "__main__":
    app = GCodeToRapidApp(0)
    app.MainLoop()
