# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.0 on Thu Jan 23 01:24:00 2025
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
import logging
# end wxGlade


class Parameters(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Parameters.__init__
        self.parent = args[0]
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetTitle("Parametre")

        sizer_main = wx.BoxSizer(wx.VERTICAL)

        sizer_content = wx.BoxSizer(wx.VERTICAL)
        sizer_main.Add(sizer_content, 1, wx.ALL | wx.EXPAND, 5)

        sizer_modul = wx.BoxSizer(wx.HORIZONTAL)
        sizer_content.Add(sizer_modul, 0, wx.ALL | wx.EXPAND, 10)

        label_2 = wx.StaticText(self, wx.ID_ANY, u"Názov Modulu:")
        sizer_modul.Add(label_2, 1, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT, 5)

        self.text_modul = wx.TextCtrl(self, wx.ID_ANY, "")
        sizer_modul.Add(self.text_modul, 3, wx.EXPAND, 0)

        sizer_proc = wx.BoxSizer(wx.HORIZONTAL)
        sizer_content.Add(sizer_proc, 0, wx.ALL | wx.EXPAND, 10)

        label_3 = wx.StaticText(self, wx.ID_ANY, "Nazov PROC:")
        sizer_proc.Add(label_3, 1, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT, 5)

        self.text_proc = wx.TextCtrl(self, wx.ID_ANY, "")
        sizer_proc.Add(self.text_proc, 3, wx.EXPAND, 0)

        sizer_workobj = wx.BoxSizer(wx.HORIZONTAL)
        sizer_content.Add(sizer_workobj, 0, wx.ALL | wx.EXPAND, 10)

        label_1 = wx.StaticText(self, wx.ID_ANY, "WorkObject:")
        sizer_workobj.Add(label_1, 1, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT, 5)

        self.text_work_obj = wx.TextCtrl(self, wx.ID_ANY, "")
        self.text_work_obj.SetToolTip(u"Príklad: 45, 90, 0")
        sizer_workobj.Add(self.text_work_obj, 3, wx.EXPAND, 0)

        sizer_nastroj = wx.BoxSizer(wx.HORIZONTAL)
        sizer_content.Add(sizer_nastroj, 0, wx.ALL | wx.EXPAND, 10)

        label_4 = wx.StaticText(self, wx.ID_ANY, "Nastroj:")
        sizer_nastroj.Add(label_4, 1, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT, 5)

        self.text_tool = wx.TextCtrl(self, wx.ID_ANY, "")
        sizer_nastroj.Add(self.text_tool, 3, wx.ALL | wx.EXPAND, 0)

        sizer_buttons = wx.StdDialogButtonSizer()
        sizer_main.Add(sizer_buttons, 0, wx.ALIGN_RIGHT | wx.ALL, 5)

        self.button_cancel = wx.Button(self, wx.ID_CANCEL, "")
        sizer_buttons.AddButton(self.button_cancel)

        self.button_ok = wx.Button(self, wx.ID_OK, "")
        sizer_buttons.AddButton(self.button_ok)

        sizer_buttons.Realize()

        self.SetSizer(sizer_main)
        sizer_main.Fit(self)

        self.SetEscapeId(self.button_cancel.GetId())

        self.Layout()
        self.Centre()
        self.load_saved_settings()

        self.button_cancel.Bind(wx.EVT_BUTTON, self.cancel)
        self.button_ok.Bind(wx.EVT_BUTTON, self.save_parameters)
        # end wxGlade

    def load_saved_settings(self):
        old_data = self.parent.app_settings.get_parameters()

        self.text_modul.SetValue(old_data.module_name)
        self.text_proc.SetValue(old_data.proc_name)
        self.text_work_obj.SetValue(old_data.workobj_name)
        self.text_tool.SetValue(old_data.tool_name)

    def cancel(self, event):  # wxGlade: Parameters.<event_handler>
        self.EndModal(wx.ID_CANCEL)
        event.Skip()

    def save_parameters(self, event):  # wxGlade: Parameters.<event_handler>
        try:
            new_data = self.parent.app_settings.get_parameters()

            new_data.module_name = self.text_modul.GetValue()
            new_data.proc_name = self.text_proc.GetValue()
            new_data.tool_name = self.text_tool.GetValue()
            new_data.workobj_name = self.text_work_obj.GetValue()
            logging.info(f"New parameters: Module={new_data.module_name}, Process={new_data.proc_name}, "f"Tool={new_data.tool_name}, WorkObj={new_data.workobj_name}")

            self.parent.save_settings()
            self.parent.update_status("Parametre boli nastavené", 100)
            self.EndModal(wx.ID_OK)


        except ValueError as e:
            wx.MessageBox(str(e), "Chyba validácie", wx.OK | wx.ICON_ERROR)
            self.parent.update_status("Chyba nastavenia parametrov", 0)

        event.Skip()

# end of class Parameters
