# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.0 on Tue Feb  4 15:20:01 2025
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
import logging
# end wxGlade


class Speed(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Speed.__init__
        self.parent = args[0]
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetTitle("Speed")

        sizer_main = wx.BoxSizer(wx.VERTICAL)

        sizer_container = wx.BoxSizer(wx.VERTICAL)
        sizer_main.Add(sizer_container, 1, wx.EXPAND, 0)

        grid_sizer_speed_zone = wx.GridSizer(1, 2, 0, 0)
        sizer_container.Add(grid_sizer_speed_zone, 0, wx.ALL | wx.EXPAND, 0)

        label_zone = wx.StaticText(self, wx.ID_ANY, u"Zóny:")
        grid_sizer_speed_zone.Add(label_zone, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 30)

        self.text_zone = wx.TextCtrl(self, wx.ID_ANY, "")
        self.text_zone.SetToolTip(u"Zóna - presnosť dosiahnutia pozície robotom:\n0 - presné polohovanie\n1-200 mm - povolená odchýlka")
        grid_sizer_speed_zone.Add(self.text_zone, 0, wx.ALIGN_CENTER_VERTICAL | wx.TOP, 3)

        grid_sizer_1 = wx.GridSizer(1, 2, 0, 0)
        sizer_container.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        label_1 = wx.StaticText(self, wx.ID_ANY, "Rychlost")
        grid_sizer_1.Add(label_1, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 30)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1.Add(sizer_1, 1, wx.EXPAND, 0)

        self.radio_box_1 = wx.RadioBox(self, wx.ID_ANY, "", choices=["pouzit z G-Code", "manualne nastavit"], majorDimension=1, style=wx.RA_SPECIFY_COLS)
        self.radio_box_1.SetSelection(0)
        sizer_1.Add(self.radio_box_1, 0, 0, 0)

        self.text_ctrl_1 = wx.TextCtrl(self, wx.ID_ANY, "")
        self.text_ctrl_1.Enable(False)
        sizer_1.Add(self.text_ctrl_1, 0, 0, 0)

        sizer_buttons = wx.StdDialogButtonSizer()
        sizer_main.Add(sizer_buttons, 0, wx.ALIGN_RIGHT | wx.ALL, 4)

        self.button_CANCEL = wx.Button(self, wx.ID_CANCEL, "")
        self.button_CANCEL.SetDefault()
        sizer_buttons.AddButton(self.button_CANCEL)

        self.button_APPLY = wx.Button(self, wx.ID_OK, "")
        sizer_buttons.AddButton(self.button_APPLY)

        sizer_buttons.Realize()

        self.SetSizer(sizer_main)
        sizer_main.Fit(self)

        self.Layout()
        self.Centre()
        self.load_saved_settings()

        self.radio_box_1.Bind(wx.EVT_RADIOBOX, self.change_radiobox)
        self.button_CANCEL.Bind(wx.EVT_BUTTON, self.cancel)
        self.button_APPLY.Bind(wx.EVT_BUTTON, self.save_speed_zone)
        # end wxGlade

    def load_saved_settings(self):
        conversion = self.parent.app_settings.get_conversion()
        self.text_ctrl_1.SetValue(str(conversion.arm_speed))
        self.text_zone.SetValue(str(conversion.zone))

    def cancel(self, event):  # wxGlade: Speed.<event_handler>
        self.EndModal(wx.ID_CANCEL)
        event.Skip()

    def save_speed_zone(self, event):  # wxGlade: Speed.<event_handler>
        try:
            logging.info("Attempting to save speed and zone settings...")

            if self.radio_box_1.GetSelection() == 1:
                speed = int(self.text_ctrl_1.GetValue())
                self.parent.app_settings.get_conversion().arm_speed = speed
                logging.info(f"Manual speed set to: {speed}")
            else:
                self.parent.app_settings.get_conversion().arm_speed = 0
                logging.info("Speed set to use G-code values")

            zone = int(self.text_zone.GetValue())
            self.parent.app_settings.get_conversion().zone = zone
            logging.info(f"Zone set to: {zone}")

            self.parent.settings_manager.save_all_settings(self.parent.app_settings)
            self.parent.update_status("Rýchlosť a zóna boli nastavené", 100)
            logging.info("Speed and zone settings saved successfully")
            self.EndModal(wx.ID_OK)

            gcode_text = self.parent.gcode_input.GetValue()
            if gcode_text:
                logging.info("Starting G-code conversion...")
                self.parent.update_status("Začína konverzia G-kódu...", 25)
                self.parent.start_conversion(gcode_text)

        except ValueError as e:
            logging.error(f"Speed/zone setting error: {str(e)}")
            wx.MessageBox(str(e), "Chyba vstupu", wx.ICON_ERROR)
            self.parent.update_status("Chyba nastavenia rýchlosti", 0)
            return
        event.Skip()

    def on_conversion_complete(self, rapid_code):
        if rapid_code:
            self.GetParent().rapid_output.SetValue(rapid_code)
            self.GetParent().update_status("Konverzia dokončená", 100)
            self.EndModal(wx.ID_OK)
        else:
            self.GetParent().update_status("Chyba konverzie", 0)
    def change_radiobox(self, event):  # wxGlade: Speed.<event_handler>
        use_manual = self.radio_box_1.GetSelection() == 1
        self.text_ctrl_1.Enable(use_manual)
        event.Skip()
# end of class Speed
